
search_tests = [ {'artist': 'tristam', 'track': 'once again', 'result': 'Monstercat 016 - Expedition'},
                 {'artist': 'chic', 'track': 'le freak', 'result': 'C\'est Chic'},
                 {'artist': 'pantera', 'track': 'cowboys from hell', 'result': 'Cowboys From Hell'},
                 {'artist': 'daft punk', 'track': 'robot rock', 'result': 'Human After All'},
                 {'artist': 'flight facilities', 'track': 'crave you', 'result': 'Crave You'},
                 {'artist': 'don diablo', 'track': 'silent shadows', 'result': 'Silent Shadows'},
                 {'artist': 'electric six', 'track': 'dance commander', 'result': 'Fire'},
                 {'artist': 'the mcmash clan', 'track': 'swing break', 'result': 'Circus Two (Presented by Cookie Monsta and FuntCase)'},
                 {'artist': 'john newman', 'track': 'love me again (kove remix)', 'result': 'Love Me Again'},
                 {'artist': 'pendulum', 'track': 'propane nightmares celldweller remix', 'result': 'Propane Nightmares'},
                 {'artist': 'freestylers', 'track': 'painkiller', 'result': 'Adventure in Freestyle'},
                 {'artist': 'dub fx', 'track': 'concord', 'result': 'Theory of Harmony'},
                 {'artist': 'George Morel', 'track': 'let\'s groove', 'result': 'Morel\'s Grooves 4'},
                 {'artist': 'dirtyphonics', 'track': 'dirty (metrik remix)', 'result': 'Dirty'},
                 {'artist': 'booka shade', 'track': 'body laguage - interpretation', 'result': 'GPMCD006 - Movements'},
                 {'artist': 'daft punk', 'track': 'get lucky', 'result': 'Random Access Memories'},
                 {'artist': 'don diablo', 'track': 'silent shadows (mind vortex remix)', 'result': 'Silent Shadows'},
                 {'artist': 'infected mushroom', 'track': 'saeed', 'result': 'Legend Of The Black Shawarma'},
                 {'artist': 'heaven\'s basement', 'track': 'fire, fire', 'result': 'Filthy Empire'},
                 {'artist': 'taylor swift', 'track': 'red', 'result': 'Red'},
                 {'artist': 'shinedown', 'track': 'my name', 'result': 'Amaryllis'},                  
                 {'artist': 'the rolling stones', 'track': 'paint it black', 'result': 'GRRR!'},    # GRRR! or Forty Licks
                 {'artist': 'rolling stones', 'track': 'paint it, black', 'result': 'Forty Licks'},
                 {'artist': 'blacklisted me', 'track': 'emerald eyes', 'result': 'Emerald Eyes'},
                 {'artist': 'hollywood undead', 'track': 'Dead Bite', 'result': 'Notes From The Underground'},
                 {'artist': 'bomfunk MC\'s', 'track': 'b-boys & fly girls', 'radio_edit': True, 'result': 'In Stereo'},
                 {'artist': 'a-trak', 'track': 'money makin\'', 'result': 'Money Makin\''},
                 {'artist': 'Skism', 'track': 'Experts', 'result': 'The Division'},
             ]

lastfm_apikey = '7267a8e796033112b57f12e6f7b3bf74'